version: 2
changelog:
  use: github-native
builds:
  - id: kubeadm-join-config
    main: ./cmd/kubeadm-join-config
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: binary
    name_template: "kubeadm-join-config_{{ .Version }}_{{ .Arch }}"  