apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weave-net
  labels:
    name: weave-net
rules:
  - apiGroups:
      - ""
    resourceNames:
      - weave-net
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create