k8sServiceHost: 10.0.0.10
k8sServicePort: 6443
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
operator:
  enabled: true
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    - effect: NoSchedule
      key: node.kubernetes.io/not-ready
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
ipam:
  operator:
    # TODO: sync with config/kubeadm-init.yaml
    clusterPoolIPv4PodCIDRList:
      - 10.244.0.0/16
    clusterPoolIPv4MaskSize: 24
