# TODO: update with k8s-master IP
k8sServiceHost: 192.168.0.110
k8sServicePort: 6443
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
containerRuntime:
  integration: containerd
hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
  relay:
    enabled: true
  ui:
    enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
operator:
  enabled: true
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
ipam:
  operator:
    # TODO: sync with config/kubeadm-init.yaml
    clusterPoolIPv4PodCIDRList:
      - 10.0.0.0/8
