apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "{{API_SERVER_ENDPOINT}}"
    token: "{{TOKEN}}"
    caCertHashes:
      - "{{CA_CERT_HASH}}"
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  kubeletExtraArgs:
    container-runtime: remote
    runtime-request-timeout: 15m
    container-runtime-endpoint: unix:///run/containerd/containerd.sock
  taints:
    []
    # - key: "node.cilium.io/agent-not-ready"
    #   value: "true"
    #   effect: "NoSchedule"
