apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "{{API_SERVER_ENDPOINT}}"
    token: "{{TOKEN}}"
    caCertHashes:
      - "{{CA_CERT_HASH}}"
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  kubeletExtraArgs:
    container-runtime-endpoint: unix:///run/containerd/containerd.sock
