apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    container-runtime-endpoint: unix:///run/containerd/containerd.sock
  ignorePreflightErrors:
    - Mem
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
# TODO: sync with scripts/kubernetes.sh
kubernetesVersion: v1.25.4
etcd:
  local:
    extraArgs:
      listen-metrics-urls: "http://0.0.0.0:2381"
    dataDir: /var/lib/etcd
controllerManager:
  extraArgs:
    bind-address: 0.0.0.0
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
apiServer:
  certSANs:
    - mmontes.duckdns.org
networking:
  dnsDomain: "cluster.local"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
  strictARP: true
metricsBindAddress: 0.0.0.0:10249
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
serverTLSBootstrap: true
