tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane

storageClass:
  create: true
  defaultClass: true
  defaultVolumeType: hostPath
  name: local-path
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer