apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: weave-net
  labels:
    name: weave-net
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      name: weave-net
  template:
    metadata:
      labels:
        name: weave-net
    spec:
      containers:
        - name: weave
          command:
            - /home/weave/launch.sh
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: INIT_CONTAINER
              value: "true"
          image:  "{{ .Values.images.weave.repository }}:{{ .Values.images.weave.tag }}"
          imagePullPolicy: "{{ .Values.images.weave.pullPolicy }}"
          readinessProbe:
            httpGet:
              host: 127.0.0.1
              path: /status
              port: 6784
          {{ with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end}}
          securityContext:
            privileged: true
          volumeMounts:
            - name: weavedb
              mountPath: /weavedb
            - name: dbus
              mountPath: /host/var/lib/dbus
            - name: machine-id
              mountPath: /host/etc/machine-id
              readOnly: true
            - name: xtables-lock
              mountPath: /run/xtables.lock
        - name: weave-npc
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image:  "{{ .Values.images.npc.repository }}:{{ .Values.images.npc.tag }}"
          imagePullPolicy: "{{ .Values.images.npc.pullPolicy }}"
          {{ with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12}}
          {{ end}}
          securityContext:
            privileged: true
          volumeMounts:
            - name: xtables-lock
              mountPath: /run/xtables.lock
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      initContainers:
        - name: weave-init
          command:
            - /home/weave/init.sh
          image:  "{{ .Values.images.weave.repository }}:{{ .Values.images.weave.tag }}"
          imagePullPolicy: "{{ .Values.images.weave.pullPolicy }}"
          securityContext:
            privileged: true
          volumeMounts:
            - name: cni-bin
              mountPath: /host/opt
            - name: cni-bin2
              mountPath: /host/home
            - name: cni-conf
              mountPath: /host/etc
            - name: lib-modules
              mountPath: /lib/modules
            - name: xtables-lock
              mountPath: /run/xtables.lock
      priorityClassName: system-node-critical
      restartPolicy: Always
      securityContext:
        seLinuxOptions: {}
      serviceAccountName: weave-net
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - name: weavedb
          hostPath:
            path: /var/lib/weave
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-bin2
          hostPath:
            path: /home
        - name: cni-conf
          hostPath:
            path: /etc
        - name: dbus
          hostPath:
            path: /var/lib/dbus
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: machine-id
          hostPath:
            path: /etc/machine-id
            type: FileOrCreate
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
  updateStrategy:
    type: RollingUpdate
