name: Release

on:
  push:
    tags:
      - "v*"

env:
  GORELEASER_VERSION: "v2.2.0"

jobs:
  goreleaser:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: ${{ env.GORELEASER_VERSION }}
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}